### ISSUE TITLE
Crash on scheduled update

### ISSUE THREAD

**Issue by nadar71** [nadar71/EarthquakeWatchdog#92]
When the is in background or not active, scheduled update gives this error : 
2019-07-22 14:57:42.214 4090-4090/com.indiewalk.watchdog.earthquake E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.indiewalk.watchdog.earthquake, PID: 4090
    java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.indiewalk.watchdog.earthquake/.net.EarthquakeSyncIntentService }: app is in background uid UidRecord{5f15979 u0a1636 TRNB idle change:uncached procs:1 seq(0,0,0)}
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1531)
        at android.app.ContextImpl.startService(ContextImpl.java:1487)
        at android.content.ContextWrapper.startService(ContextWrapper.java:660)
        at com.indiewalk.watchdog.earthquake.net.EarthquakeNetworkDataSource.startFetchEarthquakeService(EarthquakeNetworkDataSource.java:99)
        at com.indiewalk.watchdog.earthquake.net.EarthquakeFirebaseJobService.onStartJob(EarthquakeFirebaseJobService.java:28)
        at com.firebase.jobdispatcher.JobService$2.run(JobService.java:164)
        at android.os.Handler.handleCallback(Handler.java:794)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6635)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by nadar71** [comment]
Here is the solution; it depends from sdk_int>=Build.VERSION_CODES.O
https://stackoverflow.com/questions/46445265/android-8-0-java-lang-illegalstateexception-not-allowed-to-start-service-inten
